/**
 * Recall Command
 *
 * Natural language entity queries for Claude Code integration.
 * Outputs clean, readable information that Claude can synthesize.
 *
 * Usage:
 *   kyberbot recall "John Smith"
 *   kyberbot recall "What do I know about Acme Corp?"
 *   kyberbot recall "My Projects"
 */

import { Command } from 'commander';
import {
  getEntityContext,
  searchEntities,
  getEntityGraphStats,
  getMostMentionedEntities,
  getEntityGraphDb,
  getTypedRelationships,
  getEntityProfile,
  getOpenContradictions,
  getEntityInsights,
} from '../brain/entity-graph.js';
import { formatRelationship } from '../brain/relationship-extractor.js';
import { getFactsForEntity } from '../brain/fact-store.js';
import {
  queryTimeline,
  getRecentActivity,
  getTimelineDb,
} from '../brain/timeline.js';
import { getSleepDb } from '../brain/sleep/db.js';
import { getRoot } from '../config.js';

// ═══════════════════════════════════════════════════════════════════════════════
// QUERY PARSING
// ═══════════════════════════════════════════════════════════════════════════════

function extractEntityName(query: string): string {
  // Remove common question patterns
  return query
    .replace(/^(who is|what is|what do (i|you) know about|tell me about|recall)\s+/i, '')
    .replace(/\?+$/, '')
    .trim();
}

// ═══════════════════════════════════════════════════════════════════════════════
// OUTPUT FORMATTERS (clean, no chalk, readable by Claude)
// ═══════════════════════════════════════════════════════════════════════════════

async function formatEntityContext(
  context: NonNullable<Awaited<ReturnType<typeof getEntityContext>>>,
  root: string
): Promise<string> {
  const { entity, mentions, related_entities } = context;
  const lines: string[] = [];

  // Header
  lines.push(`# ${entity.name}`);
  lines.push('');

  // Narrative profile (generated by sleep agent)
  try {
    const profile = await getEntityProfile(root, entity.id);
    if (profile) {
      lines.push(profile.profile);
      lines.push('');
    }
  } catch {
    // Non-critical
  }

  lines.push(`Mentioned ${entity.mention_count} times | First seen: ${new Date(entity.first_seen).toLocaleDateString()} | Last seen: ${new Date(entity.last_seen).toLocaleDateString()}`);
  lines.push(`Type: ${entity.type}`);

  if (entity.aliases.length > 0) {
    lines.push(`Also known as: ${entity.aliases.join(', ')}`);
  }

  // Known facts from the fact store
  try {
    const facts = await getFactsForEntity(root, entity.name, { latestOnly: true, limit: 10 });
    if (facts.length > 0) {
      lines.push('');
      lines.push('## Known Facts');
      for (const fact of facts) {
        const conf = fact.confidence < 0.7 ? ` (${Math.round(fact.confidence * 100)}%)` : '';
        lines.push(`- ${fact.content}${conf}`);
      }
    }
  } catch {
    // Non-critical
  }

  // Typed relationships (e.g., "founded", "works_at")
  try {
    const typedRels = await getTypedRelationships(root, entity.id);
    if (typedRels.length > 0) {
      lines.push('');
      lines.push('## Relationships');
      for (const rel of typedRels) {
        const verb = formatRelationship(rel.entity.name, rel.relationship, rel.direction);
        const confidence = rel.confidence >= 0.8 ? '' : ` (${Math.round(rel.confidence * 100)}% confident)`;
        lines.push(`- ${entity.name} ${verb} ${rel.entity.name}${confidence}`);
        if (rel.rationale) {
          lines.push(`  -- ${rel.rationale}`);
        }
      }
    }
  } catch {
    // Non-critical, continue without typed relationships
  }

  // Entity insights from reasoning engine
  try {
    const insights = await getEntityInsights(root, entity.id);
    if (insights.length > 0) {
      lines.push('');
      lines.push('## Insights');
      for (const insight of insights.slice(0, 5)) {
        const tag = insight.insight_type === 'inference' ? 'inferred'
          : insight.insight_type === 'pattern' ? 'pattern'
          : insight.insight_type === 'quality' ? 'note'
          : 'insight';
        lines.push(`- ${insight.insight} [${tag}]`);
      }
    }
  } catch {
    // Non-critical
  }

  // Open contradictions
  try {
    const contradictions = await getOpenContradictions(root, entity.id);
    if (contradictions.length > 0) {
      lines.push('');
      for (const c of contradictions) {
        lines.push(`Note: I have conflicting info — "${c.fact_a}" vs "${c.fact_b}". Want to clarify which is correct?`);
      }
    }
  } catch {
    // Non-critical
  }

  // Mentions with context
  if (mentions.length > 0) {
    lines.push('');
    lines.push('## Mentions');
    for (const mention of mentions.slice(0, 10)) {
      const date = new Date(mention.timestamp).toLocaleDateString();
      if (mention.context) {
        lines.push(`- [${date}] ${mention.context}`);
      } else {
        lines.push(`- [${date}] Mentioned in conversation`);
      }
    }
    if (mentions.length > 10) {
      lines.push(`- ... and ${mentions.length - 10} more mentions`);
    }
  }

  // Co-occurred entities (simpler relationships)
  if (related_entities.length > 0) {
    lines.push('');
    lines.push('## Co-occurred With');
    for (const rel of related_entities.slice(0, 10)) {
      lines.push(`- ${rel.entity.name} (${rel.entity.type}) - appeared together ${rel.strength} time(s)`);
    }
  }

  return lines.join('\n');
}

function formatSearchResults(results: Awaited<ReturnType<typeof searchEntities>>): string {
  if (results.length === 0) {
    return 'No matching entities found.';
  }

  const lines: string[] = ['# Search Results', ''];

  for (const entity of results) {
    lines.push(`- ${entity.name} (${entity.type}) - ${entity.mention_count} mention(s)`);
  }

  return lines.join('\n');
}

function formatStats(stats: Awaited<ReturnType<typeof getEntityGraphStats>>): string {
  const lines: string[] = [
    '# Entity Graph Summary',
    '',
    `Total entities tracked: ${stats.total_entities}`,
    `Total mentions recorded: ${stats.total_mentions}`,
    `Entity relationships: ${stats.total_relations}`,
    '',
    '## By Type',
    `- People: ${stats.by_type.person}`,
    `- Companies: ${stats.by_type.company}`,
    `- Projects: ${stats.by_type.project}`,
    `- Places: ${stats.by_type.place}`,
    `- Topics: ${stats.by_type.topic}`,
  ];

  return lines.join('\n');
}

function formatTopEntities(entities: Awaited<ReturnType<typeof getMostMentionedEntities>>): string {
  if (entities.length === 0) {
    return 'No entities recorded yet.';
  }

  const lines: string[] = ['# Most Mentioned Entities', ''];

  for (const entity of entities) {
    lines.push(`- ${entity.name} (${entity.type}) - ${entity.mention_count} mention(s)`);
  }

  return lines.join('\n');
}

// ═══════════════════════════════════════════════════════════════════════════════
// MEMORY GRAPH INTEGRATION
// ═══════════════════════════════════════════════════════════════════════════════

async function getRelatedMemories(root: string, entityName: string): Promise<string[]> {
  try {
    const timeline = await getTimelineDb(root);
    const sleep = getSleepDb(root);

    // Find source_paths where this entity appears (via tags or title)
    const entityLower = entityName.toLowerCase();
    const sourcePaths = timeline.prepare(`
      SELECT DISTINCT source_path FROM timeline_events
      WHERE LOWER(title) LIKE ? OR LOWER(tags_json) LIKE ? OR LOWER(entities_json) LIKE ?
      LIMIT 20
    `).all(`%${entityLower}%`, `%${entityLower}%`, `%${entityLower}%`) as Array<{ source_path: string }>;

    if (sourcePaths.length === 0) return [];

    // Single IN-clause edge fetch instead of one query per source_path (was up
    // to 20 SQLite round-trips). Walk all edges in confidence-DESC order and
    // assign top-3-considered per source — preserving original LIMIT-3-per-
    // source semantics where an edge counts toward the 3 even if it gets
    // filtered out for pointing back to another source_path in our set.
    const sourcePathArr = sourcePaths.map(s => s.source_path);
    const placeholders = sourcePathArr.map(() => '?').join(',');
    const allEdges = sleep.prepare(`
      SELECT from_path, to_path, confidence, shared_tags
      FROM memory_edges
      WHERE from_path IN (${placeholders}) OR to_path IN (${placeholders})
      ORDER BY confidence DESC
    `).all(...sourcePathArr, ...sourcePathArr) as Array<{
      from_path: string;
      to_path: string;
      confidence: number;
      shared_tags: string;
    }>;

    const pathSet = new Set(sourcePathArr);
    const consideredCount = new Map<string, number>();
    const relatedPaths = new Set<string>();

    for (const edge of allEdges) {
      const fromIsSource = pathSet.has(edge.from_path);
      const toIsSource = pathSet.has(edge.to_path);

      if (fromIsSource) {
        const c = consideredCount.get(edge.from_path) ?? 0;
        if (c < 3) {
          consideredCount.set(edge.from_path, c + 1);
          if (!toIsSource) relatedPaths.add(edge.to_path);
        }
      }
      if (toIsSource) {
        const c = consideredCount.get(edge.to_path) ?? 0;
        if (c < 3) {
          consideredCount.set(edge.to_path, c + 1);
          if (!fromIsSource) relatedPaths.add(edge.from_path);
        }
      }
    }

    if (relatedPaths.size === 0) return [];

    // Single IN-clause title fetch instead of one query per related path.
    const relArr = [...relatedPaths];
    const titlePlaceholders = relArr.map(() => '?').join(',');
    const items = timeline.prepare(`
      SELECT source_path, title, tier, timestamp
      FROM timeline_events
      WHERE source_path IN (${titlePlaceholders})
    `).all(...relArr) as Array<{
      source_path: string;
      title: string;
      tier: string;
      timestamp: string;
    }>;
    const byPath = new Map(items.map(i => [i.source_path, i]));

    // Iterate the Set so output order matches the original (insertion order
    // from the edge walk). Drop entries with no timeline row.
    const lines: string[] = [];
    for (const path of relatedPaths) {
      const item = byPath.get(path);
      if (item) {
        const date = new Date(item.timestamp).toLocaleDateString();
        lines.push(`- ${item.title} [${date}] (${item.tier})`);
      }
    }

    return lines;
  } catch {
    return [];
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// COMMAND HANDLER
// ═══════════════════════════════════════════════════════════════════════════════

async function handleRecall(query: string | undefined) {
  try {
    const root = getRoot();

    // No query = show summary
    if (!query) {
      const stats = await getEntityGraphStats(root);
      console.log(formatStats(stats));
      console.log('');

      const top = await getMostMentionedEntities(root, { limit: 10 });
      console.log(formatTopEntities(top));
      return;
    }

    // Extract entity name from natural language
    const entityName = extractEntityName(query);

    // Try exact match first
    const context = await getEntityContext(root, entityName);

    if (context) {
      console.log(await formatEntityContext(context, root));

      // Show connected memories from sleep agent graph
      const relatedMemories = await getRelatedMemories(root, entityName);
      if (relatedMemories.length > 0) {
        console.log('');
        console.log('## Connected Memories');
        for (const line of relatedMemories) {
          console.log(line);
        }
      }

      await trackEntityAccess(root, context.entity.id);
      return;
    }

    // Try search
    const results = await searchEntities(root, entityName, { limit: 10 });

    if (results.length === 1) {
      // Single match - show full context
      const singleContext = await getEntityContext(root, results[0].id);
      if (singleContext) {
        console.log(await formatEntityContext(singleContext, root));

        const relatedMemories = await getRelatedMemories(root, results[0].name);
        if (relatedMemories.length > 0) {
          console.log('');
          console.log('## Connected Memories');
          for (const line of relatedMemories) {
            console.log(line);
          }
        }

        await trackEntityAccess(root, singleContext.entity.id);
        return;
      }
    }

    if (results.length > 0) {
      console.log(formatSearchResults(results));
      return;
    }

    // Nothing found
    console.log(`No information found about "${entityName}".`);
    console.log('');
    console.log('This entity has not been mentioned in any processed conversations yet.');

  } catch (error) {
    console.error(`Error: ${error}`);
    process.exit(1);
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// ACCESS TRACKING
// ═══════════════════════════════════════════════════════════════════════════════

async function trackEntityAccess(root: string, entityId: number): Promise<void> {
  try {
    const db = await getEntityGraphDb(root);
    db.prepare(`
      UPDATE entities
      SET access_count = access_count + 1,
          last_accessed = datetime('now')
      WHERE id = ?
    `).run(entityId);
  } catch {
    // Non-critical, ignore failures
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// COMMAND DEFINITION
// ═══════════════════════════════════════════════════════════════════════════════

export function createRecallCommand(): Command {
  return new Command('recall')
    .description('Query what you know about a person, project, or topic')
    .argument('[query]', 'Entity name or natural language question')
    .action(handleRecall);
}
